package com.easygeek.classes;
// Generated 3 avr. 2015 10:14:55 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ordinateur generated by hbm2java
 */
@Entity
@Table(name = "Ordinateur", catalog = "easygeek")
public class Ordinateur implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private OrdinateurId id;
	private Float quantite;

	public Ordinateur() {
	}

	public Ordinateur(OrdinateurId id) {
		this.id = id;
	}

	public Ordinateur(OrdinateurId id, Float quantite) {
		this.id = id;
		this.quantite = quantite;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "reference", column = @Column(name = "reference", nullable = false)),
			@AttributeOverride(name = "commandeId", column = @Column(name = "commande_id", nullable = false)) })
	public OrdinateurId getId() {
		return this.id;
	}

	public void setId(OrdinateurId id) {
		this.id = id;
	}

	@Column(name = "quantite", precision = 12, scale = 0)
	public Float getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Float quantite) {
		this.quantite = quantite;
	}

}
