package com.easygeek.classes;
// Generated 3 avr. 2015 10:14:55 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdinateurId generated by hbm2java
 */
@Embeddable
public class OrdinateurId implements java.io.Serializable {

	private String reference;
	private int commandeId;

	public OrdinateurId() {
	}

	public OrdinateurId(String reference, int commandeId) {
		this.reference = reference;
		this.commandeId = commandeId;
	}

	@Column(name = "reference", nullable = false)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "commande_id", nullable = false)
	public int getCommandeId() {
		return this.commandeId;
	}

	public void setCommandeId(int commandeId) {
		this.commandeId = commandeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdinateurId))
			return false;
		OrdinateurId castOther = (OrdinateurId) other;

		return ((this.getReference() == castOther.getReference()) || (this
				.getReference() != null && castOther.getReference() != null && this
				.getReference().equals(castOther.getReference())))
				&& (this.getCommandeId() == castOther.getCommandeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReference() == null ? 0 : this.getReference().hashCode());
		result = 37 * result + this.getCommandeId();
		return result;
	}

}
