package com.easygeek.entite;
// Generated 13 avr. 2015 08:45:54 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Composant generated by hbm2java
 */
@Entity
@Table(name = "Composant", catalog = "easygeek")
public class Composant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String reference;
	private String nom;
	private String description;
	private Double prixHt;
	private Integer marqueId;
	private Integer typeId;
	private String image;

	public Composant() {
	}

	public Composant(String reference) {
		this.reference = reference;
	}

	public Composant(String reference, String nom, String description,
			Double prixHt, Integer marqueId, Integer typeId, String image) {
		super();
		this.reference = reference;
		this.nom = nom;
		this.description = description;
		this.prixHt = prixHt;
		this.marqueId = marqueId;
		this.typeId = typeId;
		this.image = image;
	}

	@Id
	@Column(name = "reference", unique = true, nullable = false)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Prix_HT", precision = 22, scale = 0)
	public Double getPrixHt() {
		return this.prixHt;
	}

	public void setPrixHt(Double prixHt) {
		this.prixHt = prixHt;
	}

	@Column(name = "marque_id")
	public Integer getMarqueId() {
		return this.marqueId;
	}

	public void setMarqueId(Integer marqueId) {
		this.marqueId = marqueId;
	}

	@Column(name = "Type_id")
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "image", length = 65535)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
