package com.easygeek.entite;
// Generated 6 avr. 2015 19:09:30 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DetailsCommande generated by hbm2java
 */
@Entity
@Table(name = "Details_commande", catalog = "easygeek")
public class DetailsCommande implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private DetailsCommandeId id;
	private Float quantite;

	public DetailsCommande() {
	}

	public DetailsCommande(DetailsCommandeId id) {
		this.id = id;
	}

	public DetailsCommande(DetailsCommandeId id, Float quantite) {
		this.id = id;
		this.quantite = quantite;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "reference", column = @Column(name = "reference", nullable = false)),
			@AttributeOverride(name = "commandeId", column = @Column(name = "commande_id", nullable = false)) })
	public DetailsCommandeId getId() {
		return this.id;
	}

	public void setId(DetailsCommandeId id) {
		this.id = id;
	}

	@Column(name = "quantite", precision = 12, scale = 0)
	public Float getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Float quantite) {
		this.quantite = quantite;
	}

}
