package com.easygeek.entite;
// Generated 13 avr. 2015 14:02:45 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "Stock", catalog = "easygeek")
public class Stock implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer idStock;
	private String reference;
	private Date dateStock;
	private Boolean reapprovisionnement;
	private Integer quantite;
	private Fournisseur fournisseurId;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdStock",unique = true, nullable = false)
	public Integer getId() {
		return this.idStock;
	}

	public void setId(Integer idStock) {
		this.idStock = idStock;
	}
	
	@Column(name = "reference", nullable = false)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_stock", length = 19)
	public Date getDate() {
		return this.dateStock;
	}

	public void setDate(Date dateStock) {
		this.dateStock = dateStock;
	}

	@Column(name = "reapprovisionnement")
	public Boolean getReapprovisionnement() {
		return this.reapprovisionnement;
	}

	public void setReapprovisionnement(Boolean reapprovisionnement) {
		this.reapprovisionnement = reapprovisionnement;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="Fournisseur_id")
	public Fournisseur getFournisseurId() {
		return fournisseurId;
	}

	public void setFournisseurId(Fournisseur fournisseurId) {
		this.fournisseurId = fournisseurId;
	}
	
//	@Column(name = "Fournisseur_id",nullable = false)
//	public Integer getFournisseurId() {
//		return fournisseurId;
//	}
//
//	public void setFournisseurId(Integer fournisseurId) {
//		this.fournisseurId = fournisseurId;
//	}


}
