package com.easygeek.entite;
// Generated 6 avr. 2015 19:09:30 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "easygeek")
public class Stock implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Date date;
	private Boolean reapprovisionnement;
	private Integer quantite;
	private String reference;

	public Stock() {
	}

	public Stock(Integer id, Date date, Boolean reapprovisionnement,
			Integer quantite, String reference) {
		super();
		this.id = id;
		this.date = date;
		this.reapprovisionnement = reapprovisionnement;
		this.quantite = quantite;
		this.reference = reference;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stock_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_stock", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "reapprovisionnement")
	public Boolean getReapprovisionnement() {
		return this.reapprovisionnement;
	}

	public void setReapprovisionnement(Boolean reapprovisionnement) {
		this.reapprovisionnement = reapprovisionnement;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@Column(name = "reference")
	public String getReference() {
		return reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
